# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Vuejs Build & Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Yarn Install
      run: yarn
    - name: Yarn Run Build
      run: yarn build
    - name: Upload Dist release
      uses: actions/upload-artifact@v4
      with:
        name: HTML Build Artifacts
        path: dist
